// LOADING CONSTANTS
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

// MESSAGE/ERROR CONSTANTS
export const GET_MSG = 'GET_MSG';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_MSG = 'CLEAR_MSG';

export const TOKEN_EXPIRE = 'TOKEN_EXPIRE';

// AUTH CONSTANTS
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

// MESSAGE/ERROR CONSTANTS
export const POST_BLOG_SUCCESS = 'POST_BLOG_SUCCESS';
export const POST_BLOG_FAIL = 'POST_BLOG_FAIL';
export const GET_USER_BLOG_SUCCESS = 'GET_USER_BLOG_SUCCESS';
export const GET_USER_BLOG_FAIL = 'GET_USER_BLOG_FAIL';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_FAIL = 'GET_ALL_BLOG_FAIL';
export const GET_BLOG_DETAIL_SUCCESS = 'GET_BLOG_DETAIL_SUCCESS';
export const GET_BLOG_DETAIL_FAIL = 'GET_BLOG_DETAIL_FAIL';
